<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Program_2" Id="{17ffc23a-7847-4f66-8f73-a9451c7df59b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Program_2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Program_2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>