<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Program_1" Id="{8baa3dab-cece-4a1e-9c5e-978e8968a86a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Program_1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Program_1">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>